### ISSUE TITLE
Timeouts when querying PyPI

### ISSUE THREAD

**Issue by edmorley** [brettcannon/caniusepython3#116]
**STR:**
1. Clone https://github.com/mozilla/treeherder
2. Update to revision 985cd86a6de3b33a5025b7152be4f29804456eba
3. From the root of the repo, run: `caniusepython3 -r requirements/common.txt`

**Expected:**
Command succeeds.

**Actual:**
```
Finding and checking dependencies ...
Traceback (most recent call last):
  File "/usr/bin/caniusepython3", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/caniusepython3/__main__.py", line 179, in main
    check(projects_from_cli(args))
  File "/usr/lib/python2.7/site-packages/caniusepython3/__main__.py", line 167, in check
    blockers = dependencies.blocking_dependencies(projects, pypi.all_py3_projects())
  File "/usr/lib/python2.7/site-packages/caniusepython3/pypi.py", line 112, in all_py3_projects
    for result in map(projects_matching_classifier, py3_classifiers()):
  File "/usr/lib/python2.7/site-packages/caniusepython3/pypi.py", line 98, in projects_matching_classifier
    for result in client.browse([classifier]))
  File "/usr/lib/python2.7/xmlrpclib.py", line 1240, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1599, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1280, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1313, in single_request
    return self.parse_response(response)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1490, in parse_response
    return u.close()
  File "/usr/lib/python2.7/xmlrpclib.py", line 799, in close
    raise Fault(**self._stack[0])
xmlrpclib.Fault: <Fault 1: "<class 'psycopg2.extensions.QueryCanceledError'>:canceling statement due to statement timeout\n">
```
Run using Python 2.7.11 on MSYS2.

**Comment by edmorley** [comment]
If I try the web version that also doesn't work.

eg:
https://caniusepython3.com/ -> https://raw.githubusercontent.com/mozilla/treeherder/master/requirements/common.txt
-> stuck on "Please wait we're checking your projects"

**Comment by brettcannon** [comment]
That error isn't a bug from caniusepython3 but PyPI timing out. I should probably raise a better exception when it happens, though.

**Comment by playpauseandstop** [comment]
Have same error even on easy case while running `caniusepython3 -p Django`. First I think it's about my connection, but after error repeats on EC2 & DigitalOcean instances as well. In same time status.python.org is all green and response time for PyPI requests is decent. Any ideas on why `caniusepython3` doesn't work?

Python 2.7.10 if it matters (I tried to run it on Python 3.5.1, but had same results)

```
/.../venv/bin/caniusepython3 -p Django
Finding and checking dependencies ...
Traceback (most recent call last):
  File "/.../venv/bin/caniusepython3", line 11, in <module>
    sys.exit(main())
  File "/.../venv/local/lib/python2.7/site-packages/caniusepython3/__main__.py", line 179, in main
    check(projects_from_cli(args))
  File "/.../venv/local/lib/python2.7/site-packages/caniusepython3/__main__.py", line 167, in check
    blockers = dependencies.blocking_dependencies(projects, pypi.all_py3_projects())
  File "/.../venv/local/lib/python2.7/site-packages/caniusepython3/pypi.py", line 112, in all_py3_projects
    for result in map(projects_matching_classifier, py3_classifiers()):
  File "/.../venv/local/lib/python2.7/site-packages/caniusepython3/pypi.py", line 98, in projects_matching_classifier
    for result in client.browse([classifier]))
  File "/usr/lib/python2.7/xmlrpclib.py", line 1240, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1599, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1280, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1313, in single_request
    return self.parse_response(response)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1490, in parse_response
    return u.close()
  File "/usr/lib/python2.7/xmlrpclib.py", line 799, in close
    raise Fault(**self._stack[0])
xmlrpclib.Fault: <Fault 1: "<class 'psycopg2.extensions.QueryCanceledError'>:canceling statement due to statement timeout\n">
```

**ps.** And sad story here, that today I had an internal talk in my company about Python 3 benefits and wanted to illustrate that Python 3 is much closer than other devs think, but couldn't confirm it easily :(

**Comment by brettcannon** [comment]
So the error has nothing to do with PyPI being down, just not being able to serve a specific request in time (caniusepython3 has to request some data that can be a little hard on PyPI's database).

You can always try using https://caniusepython3.com/ to get results as well (disclaimer: I don't run the site).

**Comment by brettcannon** [comment]
I should try using https://pypi.io/pypi as the endpoint instead of pypi.python.org/pypi to see if that improves things. Since there's a possible good solution I'm also flagging this as a bug until I find out if pypi.io resolves this issue nicely.

**Comment by brettcannon** [comment]
Using pypi.io seems to help, so moving this back to an enhancement as the timeouts should be scaled back.

**Comment by brettcannon** [comment]
Timeout failures from pypi.io [trigger](https://travis-ci.org/brettcannon/caniusepython3/jobs/137925538) a `xmlrpc.client.ProtocolError: <ProtocolError for pypi.io/pypi: 503 Connection timed out>`. Checking the [`errorcode` attribute](https://docs.python.org/3/library/xmlrpc.client.html#xmlrpc.client.ProtocolError.errcode) as being `>= 500` should cover this case.

**Comment by brettcannon** [comment]
I should mention that this will fix the CI, but won't necessarily solve users having issues. Might need to catch this sort of exception at a high level and print a message saying PyPI is having issues or something.
