### ISSUE TITLE
New PyPI release needed

### ISSUE THREAD

**Issue by jmbowman** [brettcannon/caniusepython3#145]
It looks like the release currently on PyPI fails due to a change in the allowed protocols for API access to PyPI:

```
Finding and checking dependencies ...
Traceback (most recent call last):
  File "/Users/jeremybowman/.virtualenvs/bok-choy/bin/caniusepython3", line 11, in <module>
    sys.exit(main())
  File "/Users/jeremybowman/.virtualenvs/bok-choy/lib/python2.7/site-packages/caniusepython3/__main__.py", line 179, in main
    check(projects_from_cli(args))
  File "/Users/jeremybowman/.virtualenvs/bok-choy/lib/python2.7/site-packages/caniusepython3/__main__.py", line 167, in check
    blockers = dependencies.blocking_dependencies(projects, pypi.all_py3_projects())
  File "/Users/jeremybowman/.virtualenvs/bok-choy/lib/python2.7/site-packages/caniusepython3/pypi.py", line 112, in all_py3_projects
    for result in map(projects_matching_classifier, py3_classifiers()):
  File "/Users/jeremybowman/.virtualenvs/bok-choy/lib/python2.7/site-packages/caniusepython3/pypi.py", line 98, in projects_matching_classifier
    for result in client.browse([classifier]))
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 1240, in __call__
    return self.__send(self.__name, args)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 1599, in __request
    verbose=self.__verbose
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 1280, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 1328, in single_request
    response.msg,
xmlrpclib.ProtocolError: <ProtocolError for pypi.python.org/pypi: 403 Must access using HTTPS instead of HTTP>
```

Current master works, as it changed to use HTTPS (and uses a different server).

**Comment by brettcannon** [comment]
I'm planning to do a new release this week.

**Comment by brettcannon** [comment]
Done! https://pypi.io/project/caniusepython3/

**Comment by jmbowman** [comment]
Great, thanks!
