### ISSUE TITLE
running fails due to SSL CERTIFICATE_VERIFY_FAILED errors

### ISSUE THREAD

**Issue by skk** [brettcannon/caniusepython3#173]
Example:

[WARNING] shutilwhich not found
[ERROR] Failed to get external data for https://www.red-dove.com/pypi/projects/B/browserstack-local/project.json: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)>
Traceback (most recent call last):
  File "/Users/steven.knight/.pyenv/versions/2.7.13/envs/cashbot/lib/python2.7/site-packages/distlib/util.py", line 908, in _get_external_data
    resp = urlopen(url)
  File "/Users/steven.knight/.pyenv/versions/2.7.13/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/Users/steven.knight/.pyenv/versions/2.7.13/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/Users/steven.knight/.pyenv/versions/2.7.13/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/Users/steven.knight/.pyenv/versions/2.7.13/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/Users/steven.knight/.pyenv/versions/2.7.13/lib/python2.7/urllib2.py", line 1241, in https_open

I used caniusepython3 a few weeks ago without any errors.

**Comment by brettcannon** [comment]
@vsajip it looks like the SSL cert for red-dove.com has expired.

**Comment by vsajip** [comment]
Whoops, sorry about this - certificate has now been updated.

**Comment by brettcannon** [comment]
@vsajip no problem. 😄 

@skk can you check again to see if you're still getting the error?

**Comment by skk** [comment]
it is working now!  thanks.

**Comment by benjaminrigaud** [comment]
@vsajip I have the same error about https://www.red-dove.com/ certificate. Should I open another issue?

**Comment by vsajip** [comment]
No, I'll deal with it - my Let's Encrypt renewal script appears to have failed.

**Comment by vsajip** [comment]
OK, should work now.

**Comment by benjaminrigaud** [comment]
@vsajip Yes. Thank you. Have a good day.
