### ISSUE TITLE
Package available on pypi.org but not on https://www.red-dove.com/pypi

### ISSUE THREAD

**Issue by proinsias** [brettcannon/caniusepython3#212]
(This is probably not an issue with `caniusepython3`, but I thought it would be helpful to document how to deal with it.)

`caniusepython3` complains (see below) about `fbprophet`, despite this package being [available](https://pypi.org/project/fbprophet/) on pypi.org.

This is because it's not available at <https://www.red-dove.com/pypi/projects/F/fbprophet/>, as expected by `caniusepython3`.

Is this a known issue with pypi? Is there anything a user can do to fix this? Or should a user just add an override for this package?

```
$ caniusepython3 --projects fbprophet
Finding and checking dependencies ...
[ERROR] Failed to get external data for https://www.red-dove.com/pypi/projects/F/fbprophet/project.json: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "/Users/francis/.local/pipx/venvs/caniusepython3/lib/python3.7/site-packages/distlib/util.py", line 909, in _get_external_data
    resp = urlopen(url)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
[WARNING] fbprophet not found
```

**Comment by brettcannon** [comment]
It's a bug with distlib, so a bug should be filed at https://bitbucket.org/pypa/distlib.

/cc @vsajip

**Comment by proinsias** [comment]
[Done](https://bitbucket.org/pypa/distlib/issues/128/packages-available-on-pypiorg-but-not-on).
