### ISSUE TITLE
Calls out to www.red-dove.com and fails

### ISSUE THREAD

**Issue by wimglenn** [brettcannon/caniusepython3#225]
Basic example:

```
$ caniusepython3 --verbose --project mpmath  
[INFO] 1 top-level projects to check
Finding and checking dependencies ...
[INFO] Overrides loaded from GitHub and cached
[INFO] Checking top-level project: mpmath ...
[INFO] Checking mpmath ...
[INFO] Locating dependencies for mpmath
[ERROR] Failed to get external data for https://www.red-dove.com/pypi/projects/M/mpmath/project.json: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File ".../.venv/lib/python3.9/site-packages/distlib/util.py", line 913, in _get_external_data
    resp = urlopen(url)
  File "/usr/local/Cellar/python@3.9/3.9.1_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python@3.9/3.9.1_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/usr/local/Cellar/python@3.9/3.9.1_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/usr/local/Cellar/python@3.9/3.9.1_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/usr/local/Cellar/python@3.9/3.9.1_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python@3.9/3.9.1_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
[WARNING] mpmath not found

🎉  You have 0 projects blocking you from using Python 3!

```

After a bit of digging, it seems that the error is via distlib and the website red-dove.com is from Vinay.  I'm not sure what is going on there with the 403s but have asked on the bitbucket.

A more concerning problem is that when dependencies can not be retrieved, the error passes silently.  For example, this should log that it is checking six, since structlog has a dependency on six:

```
$ caniusepython3 --verbose --project structlog
[INFO] 1 top-level projects to check
Finding and checking dependencies ...
[INFO] Overrides loaded from GitHub and cached
[INFO] Checking top-level project: structlog ...
[INFO] Checking structlog ...

🎉  You have 0 projects blocking you from using Python 3!

```

But it does not actually recurse in the first place, because of [this except + return](https://github.com/brettcannon/caniusepython3/blob/6bdfea0aebade11709d1ec524229124d77dd2563/caniusepython3/dependencies.py#L61) when the distlib locators are not working:

```
>>> from distlib.locators import locate
>>> locate("structlog") is None
True
```

**Comment by brettcannon** [comment]
There isn't much I can do here since it's all behind distlib as you deduced. The logging output does say `WARNING] mpmath not found` to try and call out that false-negatives are possible. But I just pushed a change that should make it even more obvious that false-negatives may occur.
